# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/router/Documents/muduo_example/chat_server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/router/Documents/muduo_example/chat_server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/router/Documents/muduo_example/chat_server/CMakeFiles /home/router/Documents/muduo_example/chat_server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/router/Documents/muduo_example/chat_server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chat_server

# Build rule for target.
chat_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chat_server
.PHONY : chat_server

# fast build rule for target.
chat_server/fast:
	$(MAKE) -f CMakeFiles/chat_server.dir/build.make CMakeFiles/chat_server.dir/build
.PHONY : chat_server/fast

#=============================================================================
# Target rules for targets named chat_client

# Build rule for target.
chat_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chat_client
.PHONY : chat_client

# fast build rule for target.
chat_client/fast:
	$(MAKE) -f CMakeFiles/chat_client.dir/build.make CMakeFiles/chat_client.dir/build
.PHONY : chat_client/fast

#=============================================================================
# Target rules for targets named chat_server_effective

# Build rule for target.
chat_server_effective: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chat_server_effective
.PHONY : chat_server_effective

# fast build rule for target.
chat_server_effective/fast:
	$(MAKE) -f CMakeFiles/chat_server_effective.dir/build.make CMakeFiles/chat_server_effective.dir/build
.PHONY : chat_server_effective/fast

#=============================================================================
# Target rules for targets named chat_server_highperform

# Build rule for target.
chat_server_highperform: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chat_server_highperform
.PHONY : chat_server_highperform

# fast build rule for target.
chat_server_highperform/fast:
	$(MAKE) -f CMakeFiles/chat_server_highperform.dir/build.make CMakeFiles/chat_server_highperform.dir/build
.PHONY : chat_server_highperform/fast

chat_client.o: chat_client.cc.o

.PHONY : chat_client.o

# target to build an object file
chat_client.cc.o:
	$(MAKE) -f CMakeFiles/chat_client.dir/build.make CMakeFiles/chat_client.dir/chat_client.cc.o
.PHONY : chat_client.cc.o

chat_client.i: chat_client.cc.i

.PHONY : chat_client.i

# target to preprocess a source file
chat_client.cc.i:
	$(MAKE) -f CMakeFiles/chat_client.dir/build.make CMakeFiles/chat_client.dir/chat_client.cc.i
.PHONY : chat_client.cc.i

chat_client.s: chat_client.cc.s

.PHONY : chat_client.s

# target to generate assembly for a file
chat_client.cc.s:
	$(MAKE) -f CMakeFiles/chat_client.dir/build.make CMakeFiles/chat_client.dir/chat_client.cc.s
.PHONY : chat_client.cc.s

chat_server.o: chat_server.cc.o

.PHONY : chat_server.o

# target to build an object file
chat_server.cc.o:
	$(MAKE) -f CMakeFiles/chat_server.dir/build.make CMakeFiles/chat_server.dir/chat_server.cc.o
.PHONY : chat_server.cc.o

chat_server.i: chat_server.cc.i

.PHONY : chat_server.i

# target to preprocess a source file
chat_server.cc.i:
	$(MAKE) -f CMakeFiles/chat_server.dir/build.make CMakeFiles/chat_server.dir/chat_server.cc.i
.PHONY : chat_server.cc.i

chat_server.s: chat_server.cc.s

.PHONY : chat_server.s

# target to generate assembly for a file
chat_server.cc.s:
	$(MAKE) -f CMakeFiles/chat_server.dir/build.make CMakeFiles/chat_server.dir/chat_server.cc.s
.PHONY : chat_server.cc.s

chat_server_effective.o: chat_server_effective.cc.o

.PHONY : chat_server_effective.o

# target to build an object file
chat_server_effective.cc.o:
	$(MAKE) -f CMakeFiles/chat_server_effective.dir/build.make CMakeFiles/chat_server_effective.dir/chat_server_effective.cc.o
.PHONY : chat_server_effective.cc.o

chat_server_effective.i: chat_server_effective.cc.i

.PHONY : chat_server_effective.i

# target to preprocess a source file
chat_server_effective.cc.i:
	$(MAKE) -f CMakeFiles/chat_server_effective.dir/build.make CMakeFiles/chat_server_effective.dir/chat_server_effective.cc.i
.PHONY : chat_server_effective.cc.i

chat_server_effective.s: chat_server_effective.cc.s

.PHONY : chat_server_effective.s

# target to generate assembly for a file
chat_server_effective.cc.s:
	$(MAKE) -f CMakeFiles/chat_server_effective.dir/build.make CMakeFiles/chat_server_effective.dir/chat_server_effective.cc.s
.PHONY : chat_server_effective.cc.s

chat_server_highperform.o: chat_server_highperform.cc.o

.PHONY : chat_server_highperform.o

# target to build an object file
chat_server_highperform.cc.o:
	$(MAKE) -f CMakeFiles/chat_server_highperform.dir/build.make CMakeFiles/chat_server_highperform.dir/chat_server_highperform.cc.o
.PHONY : chat_server_highperform.cc.o

chat_server_highperform.i: chat_server_highperform.cc.i

.PHONY : chat_server_highperform.i

# target to preprocess a source file
chat_server_highperform.cc.i:
	$(MAKE) -f CMakeFiles/chat_server_highperform.dir/build.make CMakeFiles/chat_server_highperform.dir/chat_server_highperform.cc.i
.PHONY : chat_server_highperform.cc.i

chat_server_highperform.s: chat_server_highperform.cc.s

.PHONY : chat_server_highperform.s

# target to generate assembly for a file
chat_server_highperform.cc.s:
	$(MAKE) -f CMakeFiles/chat_server_highperform.dir/build.make CMakeFiles/chat_server_highperform.dir/chat_server_highperform.cc.s
.PHONY : chat_server_highperform.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... chat_server"
	@echo "... edit_cache"
	@echo "... chat_client"
	@echo "... chat_server_effective"
	@echo "... chat_server_highperform"
	@echo "... chat_client.o"
	@echo "... chat_client.i"
	@echo "... chat_client.s"
	@echo "... chat_server.o"
	@echo "... chat_server.i"
	@echo "... chat_server.s"
	@echo "... chat_server_effective.o"
	@echo "... chat_server_effective.i"
	@echo "... chat_server_effective.s"
	@echo "... chat_server_highperform.o"
	@echo "... chat_server_highperform.i"
	@echo "... chat_server_highperform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

